name: "CROSS Software Portal"
author: "Sina Hamedian <sina@ucsc.edu>"
title: UCSC Software Portal
description: "Software Portal for the Center for Research in Open Source Software (CROSS)"

url: " http://uccross.github.io/"

# GitHub Metadata -- https://github.com/jekyll/github-metadata
repository: uccross/uccross.github.io
gems:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/news/:year/:month/:day/:title/"

permalink: pretty

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - README.md
    - Makefile
